#
# Travis CI config file
#

language: python

dist: 'jammy'

python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install poetry
install:
  - poetry install

# command to run tests
script:
  - pytest
