# output directory -- will create a llm/ subfolder
target_dir: .

source_dir: ..

# which modules to preprocess
module_list:
  - 'llm'
  - 'llm.llmstd'
  - 'llm.fragmentrenderer.html'
  - 'llm.fragmentrenderer.text'


skip_relative_import_prefixes:
  - 'pylatexenc'

# features
enabled_features:
  keep_future_statements: False
  keep_relative_imports: False
  keep_super_arguments: False
  keep_dict_with_generator: False
  keep_frozenset: False
  keep_logger_debug: False
  guards:
    PYTHON2_SUPPORT_CODE: False
    PYLATEXENC1_LEGACY_SUPPORT_CODE: False
    PYLATEXENC2_LEGACY_SUPPORT_CODE: False
    PYLATEXENC_GET_DEFAULT_SPECS_FN: False
    LATEXWALKER_HELPERS: False
    DEBUG_SET_EQ_ATTRIBUTE: False
  patches:
    UNIQUE_OBJECT_ID: |
      import unique_object_id
      fn_unique_object_id = unique_object_id.fn_unique_object_id
    MULTIPLE_BASE_CONSTRUCTORS: |
      def _dobaseconstructors2argslast(Me, self, args, kwargs):
        Me.__bases__[0].__init__(self)
        Me.__bases__[1].__init__(self, *args, **kwargs)
        
