
name: 'deploy-pypi'


on:
  workflow_dispatch: {}

jobs:
  deploy-pypi:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    environment: env-deploy-pypi

    steps:
      - uses: actions/checkout@v3

      - name: 'Set up uv'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '${{ matrix.python-version }}'

      - name: 'uv Build Package'
        run: 'uv build'

      - name: 'uv Publish package'
        run: 'uv publish --token ${{ secrets.PYPI_API_TOKEN }}'
