
name: 'tests-ci-js'


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: "13 20 * * 3"

jobs:
  tests-ci-js:

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.11"
        node-version:
          - "14"
          - "19"
        os:
          - 'ubuntu-latest'

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v3

      # Install NodeJS
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'

      - name: 'Setting up some node packages'
        run: 'npm i debug'

      # uv & Python are needed to transpile Python library
      - name: 'Set up uv'
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '${{ matrix.python-version }}'

      - name: 'uv sync (with buildjslib)'
        run: 'uv sync --group buildjslib'

      - name: 'Check out pylatexenc v3 sources'
        working-directory: 'flm-js'
        run: 'git clone https://github.com/phfaist/pylatexenc.git pylatexenc-src --depth=1'

      - name: 'Generate LLM JS library'
        working-directory: 'flm-js'
        run: 'uv run --no-sync python ./generate_flm_js.py --pylatexenc-src-dir=./pylatexenc-src/ --compile-tests'

      - name: 'Run JS tests'
        working-directory: 'flm-js'
        run: 'node test-flm-js/runtests.js'
