
name: 'tests-ci-js'


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "13 20 * * 3"

jobs:
  tests-ci-js:

    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.11"
        poetry-version:
          - "1.2"
        node-version:
          - "14"
          - "19"
        os:
          - 'ubuntu-latest'

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: actions/checkout@v3

      # Install NodeJS
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.python-version }}'

      # Poetry & Python are needed to transpile Python library
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'

      - name: 'Set up poetry - Run image'
        uses: abatilo/actions-poetry@v2

      - name: 'Poetry Install (with buildjslib)'
        run: poetry install --with-buildjslib

      - name: 'Check out pylatexenc v3 sources'
        run: 'git checkout https://github.com/phfaist/pylatexenc.git -b devel --depth=0'

      - name: 'Generate LLM JS library'
        working-directory: 'llm-js'
        run: 'poetry run python ./generate_llm_js.py --pylatexenc-src-dir=./pylatexenc --compile-tests'

      - name: 'Run JS tests'
        working-directory: 'llm-js'
        run: 'node test-llm-js/runtests.js'
